config/routes.rb
Rails.application.routes.draw do

  get '/posts', to: "posts#index", as: "posts"

  get '/posts/new', to: "posts#new", as: "new_post"

  get '/posts/:id', to: 'posts#show', as: "post"

  get '/posts/:id/edit', to: 'posts#edit', as: "edit_post"

  post "/posts", to: "posts#create"
  #the update route 
  patch "/posts/:id", to: "posts#update"

  #the destroy route 
  delete "/posts/:id", to: "posts#destroy"

  get '/cities', to: "cities#index"

  get '/cities/:id', to: "cities#show", as: "city_name"

  root to: 'welcome#index' 
  # get "/vagabond", to: "welcome#index"
  
  get "/users", to: "users#index", as: "users"

  get "/users/new", to: "users#new", as: "new_user"

  post "/users", to: "users#create"

  get "/users/:id", to: "users#show", as: "user"

  #sessions routes

  get "/sign_in", to: "sessions#new"  

  post "/sessions", to: "sessions#create"

  delete "/sessions", to: "sessions#destroy", as: "logout"

  #update routes

  get "/users/:id/edit", to: "users#edit", as: "edit_user"

  # The update route
  patch "/users/:id", to: "users#update" 


  get 'users/posts/:id', to: 'users#posts', as: "user_posts"

  #tagging route
  get 'tags/:tag', to: 'posts#index', as: "tag"


 
end

app/models/city.rb
class City < ActiveRecord::Base
	
	has_many :users
	has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, length: { in: 1..200 }
    has_many :taggings
    has_many :tags, through: :taggings
  	validates :content, presence: true

	belongs_to :user
	belongs_to :city

  def all_tags=(names)
      self.tags = names.split(", ").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
  Tag.find_by_name!(name).posts
end



end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, presence: true, uniqueness:true

	belongs_to :city
	has_many :posts
	

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    id = params[:id]
    @city = City.find(id)
  
  end

  # def posts
  #    p params
  #    @post = Post.find_by title: params[:id]
  #    @user = City.find_by_id(@post.user_id)
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create, :update, :destroy]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    @cities = City.all
    render :index
  end

  def new
    p "POSTS.NEW PARAMS: #{params}"
    @post = Post.new #creates post instance for form
    @post.city_id = params[:format]
    p "@post.city_id = #{@post.city_id}"
    @user = current_user
    p "POSTS.NEW @user: #{@user.email}"
    @post.user_id = @user.id
    p "@post.user_id = #{@post.user_id}"
    render :new #renders form
  end

  def show
    id = params[:id]
    @post = Post.find(params[:id])
    render :show
  end

  def edit

    id = params[:id]
    @post = Post.find(params[:id])

  end

  def create
    p "POSTS.CREATE: #{params}"
    p "params[:post]: #{params[:post]}"
    p "params[:user_id]: #{params[:user_id]}"
# byebug
    new_post = params.require(:post).permit(:title, :content, :city_id, :all_tags)
    new_post[:user_id] = params[:user_id]
    p "** new_post #{new_post}"
    post = Post.create(new_post) #magically being inserted in database
    redirect_to "/posts/#{post.id}"
  end

  def update
    post_id = params[:id]
    post = Post.find(post_id)

    #get updated data
    updated_attributes = params.require(:post).permit(:title, :content)
    #update the article 
    post.update_attributes(updated_attributes)
    #redirect to show
    redirect_to "/posts/#{post_id}"
  end

  def destroy
    id = params[:id]
    post = Post.find(id)
    post.delete
    redirect_to "/posts"
  end

  private

    def require_login
      unless current_user
        redirect_to "/sign_in"
      end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
    @user = User.new
    render :new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to "/users/#{@user.id}"
    else
      redirect_to "/sign_in"
    end
  end
  
  def destroy
    # logout
    session[:user_id] = nil
    redirect_to "/sign_in"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


   def index
    @users = User.all
    render :index
   end

   def new
    @cities = City.all
    @user = User.new

    # @user.current_city = City.find_by id: 
    render :new
   end

   def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :city_id, :password, :created_at)
    p "CREATING A USER #{user_params}"
    @user = User.create(user_params)

    login(@user) # <-- login the user
    redirect_to "/users/#{@user.id}" 
   end

   def show
      id = params[:id]
      @user = User.find(id)
      @current_user = current_user
      render :show
    end

    def edit
      id = params[:id]
      @user = User.find(id)
      render :edit
    end

    def update
      user_id = params[:id]
      user = User.find(user_id)

      # get updated data
      updated_attributes = params.require(:user).permit(:first_name, :last_name, :city_id)
      # update the user
      user.update_attributes(updated_attributes)

      #redirect to show
      redirect_to "/users/#{user.id}"  # <-- go to show
    end


    def posts
      p "IN USERS POSTS #{params}"
      @post = Post.find_by id: params[:id]
      @user = User.find_by_id(@post.user_id)
    end

    # def current_city(id)
    #   # p "*** In current_city method: #{params}"
    #   city = City.find_by id: id
    #   city.name
    # end
    # helper_method :current_city

  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def tag_links(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if @current_user == nil
      redirect_to "/sign_in"
    end
  end

  def destroy
    @current_user = session[:user_id] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/index.html.erb
<h1>Cities</h1>
<hr />
<%@cities.each do |city| %>
	  
    <div class="blurry">
	       <span><%= link_to city.name, city_name_path(city)%><span> <br>                
	  </div>



<% end %>

app/views/cities/show.html.erb
<link href='https://fonts.googleapis.com/css?family=Rubik+One' rel='stylesheet' type='text/css'>


<div class="image">
  <%= image_tag(@city.imgurl) %>
  <h1 class="city_title"><%= @city.name %></h1>
</div>



<%= button_to "Add a post to this city", new_post_path(@city.id), method: "get" %>

<div>

  <% @city.posts.reverse.each do |post| %>
  	<div class='list-group'>
  		<%= link_to post.title, user_posts_path(post) %>
  	</div>


</div>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>VagabondProjectTeam2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
	<div class="container background-splash">
<%= render 'partials/navbar' %>
<%= yield %>
	</div>
</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "VAGABOND", "/", :"data-no-turbolink" => true, class: "navbar-brand" %>  
      <!-- <a class="navbar-brand" href="/">VAGABOND</a> -->


    </div>
    <!-- @user.present? -->
    <% if current_user %>

      <%= button_to "Logout", logout_path, method: "delete", class: "red btn btn-default navbar-right navbar-btn" %>
      <%= button_to "Profile", current_user, :method => "get", class: "btn btn-default navbar-right navbar-btn" %>
      <%= button_to "Recent posts", posts_path, method: "get", class: "btn btn-default navbar-right navbar-btn" %>
      <%= button_to "Cities", cities_path, method: "get", class: "btn btn-default navbar-right navbar-btn" %>

      

    <% else %>
	    <%= button_to "Login", sign_in_path, method: "get", class: "btn btn-default navbar-right navbar-btn" %>
	    <%= button_to "Sign Up", new_user_path, method: "get", class: "btn btn-default navbar-right navbar-btn" %>
	  <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "Update Post" %>
  </p>
  <% end %>

app/views/posts/index.html.erb
<h1 class="recent-posts">Recent Posts</h1>
<% @posts.reverse.take(10).each do |post| %>


  <% city = @cities.find_by_id post.city_id %>
  <div class="blurry">

    <span class="post-title"><%= link_to post.title, post_path(post) %></span> <br>
    <%= link_to city.name, city_name_path(city) %> <br>
    <%=  post.content %>
    <p>
    <% if post.user == current_user %>
      <span class="links"><%= link_to "Edit", edit_post_path(post) %></span> | 
      <span class="links"><%= link_to "Delete", post_path(post),
      method: :delete,
      data: { confirm: 'do you really want to delete?'} %></span>
      | <span class="links"><%= link_to 'Back', user_path(post.user) %></span>
    <% else %>
        <span class="links"><%= link_to 'Back', user_path(post.user) %></span>
    <% end %>

    </p>
    <hr>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add a new city post</h1>

<%= form_for @post do |f| %>
	<%= hidden_field_tag :user_id, @post.user_id %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p><p>
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</p>

	<p>
      <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </p>

	<p>
		<%= f.collection_select(:city_id, City.all, :id, :name) %>
	</p><p>
		<%= f.submit "Add a new post about this city" %>
	</p>
<% end %> 

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p class="blurry"><%= @post.content %></p>
<div class="blurry">Tags: <%= raw tag_links(@post.all_tags)%><div>

<small><%= @post.created_at %></small>
<br/>

<% if @post.user == current_user %>
  <span class="links"><%= link_to 'Edit', edit_post_path(@post) %> | 
  <span class="links"><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure you want to delete this post' } %></span> | 
  <% end %>
   <span class="links"><%= link_to 'Back', posts_path %></span>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit User</h1>


<div>

	
	<%= form_for @user do |f| %>

	<div>
		<p> First:	<%= f.text_field :first_name %> </p>
	</div>
	<div>
	    <p> Last: <%= f.text_field :last_name %> </p>
	</div>
	<div>
		<p> City: <%= f.collection_select(:city_id, City.all, :id, :name) %> </p>
	</div>


		<%= f.submit "Update User" %>


	</div>

	

</div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %> 
 <p>
   <%= f.text_field :email, placeholder: 'Email' %>
   <%= f.text_field :first_name, placeholder: 'First Name' %>
    <%= f.text_field :last_name, placeholder: 'Last Name' %>
		<%= f.collection_select(:city_id, City.all, :id, :name) %>


    <br />
   <%= f.password_field :password, placeholder: 'Password' %>
   <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
   <%= f.submit "Signup!" %>
 </p>

 
<% end %> 

app/views/users/posts.html.erb
<div class=container-fluid>
	<h1 class="blurry"><%= @post.title %></h1>
	<h2 class="blurry"> Author: <%= @user.first_name %> <%=@user.last_name%></h2>

	<p class="blurry"><%= @post.content%></p>
	<span class="links"><%= link_to "Edit", edit_post_path(@post) %></span>

	
	<div class="blurry">Tags: <%= raw tag_links(@post.all_tags) %></div>

</div>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.first_name %></h1>
<% cityObj = City.find_by id: @user.city_id %>
<p>Your current city is: <%= cityObj.name %></p>
<p>Member since: <%= @user.created_at %></p>



<span class="links"><%= link_to "Edit", edit_user_path %></span>

<% @user.posts.reverse.each do |post| %>
	<div class='list-group'>
		<%= link_to post.title, post_path(post.id) %>
	</div>
<% end %>

app/views/welcome/index.html.erb
<!-- <div class="welcome-splash"> -->
<% content_for :head do %>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHLett8djBo62dDXj0EjCimF8Rd6E8cxg"></script>
<% end %>
<h1>A Travel-Writing Platform</h1>
<p>We shall not cease from exploration and the end of our exploring will be to arrive where we started and know the place for the first time. - T.S Eliot</p>
<!-- </div> -->

<div id="map-container">
  <div id="map-canvas"></div>
</div>
<!-- <%= javascript_include_tag "map/gmap" %> -->